name: ci

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:

  check-repo:
    runs-on: ubuntu-latest
    name: 'Check is this action in particular repo'
    if: ${{ github.event.repository.name == 'chatgpt-prompts' }}
    steps:
      - name: 'Print action info'
        run: echo "event=${{ github.event_name }} event_ref=${{ github.event.ref }} repo=${{ github.event.repository.full_name }}"

  is-push-to-main:
    runs-on: ubuntu-latest
    name: 'Is triggered by push to main?'
    needs: check-repo
    if: ${{
      (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main') &&
      ((github.event_name == 'push') || github.event_name == 'workflow_dispatch') }}
    steps:
      - name: 'Current action is triggered by push to main'
        run: 'true'

  build:
    runs-on: ubuntu-latest
    needs: check-repo
    name: Continuous integration (Node.js latest)
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: 'Print latest 5 git logs'
        run: git log --branches --all --decorate --oneline -n 5
      - name: 'Install'
        run: cd chrome-extension && yarn install
      - name: 'Build'
        run: cd chrome-extension && yarn run build
      - uses: actions/upload-artifact@v2
        with:
          name: extension
          path: chrome-extension/ext
          if-no-files-found: error

